# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_meshtoolsplugin.ui'
#
# Created: Fri Apr 19 20:29:07 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MeshToolsPlugin(object):
    def setupUi(self, MeshToolsPlugin):
        MeshToolsPlugin.setObjectName(_fromUtf8("MeshToolsPlugin"))
        MeshToolsPlugin.resize(303, 527)
        self.verticalLayout = QtGui.QVBoxLayout(MeshToolsPlugin)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(MeshToolsPlugin)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.cbBoundaryPolygons = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbBoundaryPolygons.sizePolicy().hasHeightForWidth())
        self.cbBoundaryPolygons.setSizePolicy(sizePolicy)
        self.cbBoundaryPolygons.setObjectName(_fromUtf8("cbBoundaryPolygons"))
        self.gridLayout.addWidget(self.cbBoundaryPolygons, 0, 1, 1, 1)
        self.pbNewPolygons_2 = QtGui.QPushButton(self.groupBox_2)
        self.pbNewPolygons_2.setObjectName(_fromUtf8("pbNewPolygons_2"))
        self.gridLayout.addWidget(self.pbNewPolygons_2, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(MeshToolsPlugin)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.cbLines = QtGui.QComboBox(self.groupBox)
        self.cbLines.setObjectName(_fromUtf8("cbLines"))
        self.gridLayout_6.addWidget(self.cbLines, 1, 1, 1, 1)
        self.pbNewLines = QtGui.QPushButton(self.groupBox)
        self.pbNewLines.setObjectName(_fromUtf8("pbNewLines"))
        self.gridLayout_6.addWidget(self.pbNewLines, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        self.cbPolygons = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbPolygons.sizePolicy().hasHeightForWidth())
        self.cbPolygons.setSizePolicy(sizePolicy)
        self.cbPolygons.setObjectName(_fromUtf8("cbPolygons"))
        self.gridLayout_6.addWidget(self.cbPolygons, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.pbNewPolygons = QtGui.QPushButton(self.groupBox)
        self.pbNewPolygons.setObjectName(_fromUtf8("pbNewPolygons"))
        self.gridLayout_6.addWidget(self.pbNewPolygons, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_6.addWidget(self.label_3, 2, 0, 1, 1)
        self.cbPoints = QtGui.QComboBox(self.groupBox)
        self.cbPoints.setObjectName(_fromUtf8("cbPoints"))
        self.gridLayout_6.addWidget(self.cbPoints, 2, 1, 1, 1)
        self.pbNewPoints = QtGui.QPushButton(self.groupBox)
        self.pbNewPoints.setObjectName(_fromUtf8("pbNewPoints"))
        self.gridLayout_6.addWidget(self.pbNewPoints, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.line_2 = QtGui.QFrame(MeshToolsPlugin)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_6 = QtGui.QLabel(MeshToolsPlugin)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.cbAlgorithm = QtGui.QComboBox(MeshToolsPlugin)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbAlgorithm.sizePolicy().hasHeightForWidth())
        self.cbAlgorithm.setSizePolicy(sizePolicy)
        self.cbAlgorithm.setObjectName(_fromUtf8("cbAlgorithm"))
        self.horizontalLayout.addWidget(self.cbAlgorithm)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.swAlgorithmControls = QtGui.QStackedWidget(MeshToolsPlugin)
        self.swAlgorithmControls.setFrameShape(QtGui.QFrame.NoFrame)
        self.swAlgorithmControls.setFrameShadow(QtGui.QFrame.Plain)
        self.swAlgorithmControls.setObjectName(_fromUtf8("swAlgorithmControls"))
        self.pageEasyMesh = QtGui.QWidget()
        self.pageEasyMesh.setObjectName(_fromUtf8("pageEasyMesh"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pageEasyMesh)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.wEdgeLength = QtGui.QWidget(self.pageEasyMesh)
        self.wEdgeLength.setEnabled(True)
        self.wEdgeLength.setObjectName(_fromUtf8("wEdgeLength"))
        self.gridLayout_3 = QtGui.QGridLayout(self.wEdgeLength)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.wEdgeLength)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.rbLengthFromLayer = QtGui.QRadioButton(self.wEdgeLength)
        self.rbLengthFromLayer.setChecked(False)
        self.rbLengthFromLayer.setObjectName(_fromUtf8("rbLengthFromLayer"))
        self.gridLayout_3.addWidget(self.rbLengthFromLayer, 2, 0, 1, 2)
        self.cbLength = QtGui.QComboBox(self.wEdgeLength)
        self.cbLength.setEnabled(False)
        self.cbLength.setObjectName(_fromUtf8("cbLength"))
        self.gridLayout_3.addWidget(self.cbLength, 2, 2, 1, 1)
        self.rbLengthFixed = QtGui.QRadioButton(self.wEdgeLength)
        self.rbLengthFixed.setChecked(True)
        self.rbLengthFixed.setObjectName(_fromUtf8("rbLengthFixed"))
        self.gridLayout_3.addWidget(self.rbLengthFixed, 1, 0, 1, 1)
        self.leLength = QtGui.QLineEdit(self.wEdgeLength)
        self.leLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leLength.setObjectName(_fromUtf8("leLength"))
        self.gridLayout_3.addWidget(self.leLength, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.wEdgeLength)
        self.wEdgeType = QtGui.QWidget(self.pageEasyMesh)
        self.wEdgeType.setEnabled(True)
        self.wEdgeType.setObjectName(_fromUtf8("wEdgeType"))
        self.gridLayout_5 = QtGui.QGridLayout(self.wEdgeType)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setVerticalSpacing(3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.sbType = QtGui.QSpinBox(self.wEdgeType)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbType.sizePolicy().hasHeightForWidth())
        self.sbType.setSizePolicy(sizePolicy)
        self.sbType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbType.setMinimum(1)
        self.sbType.setMaximum(9999)
        self.sbType.setObjectName(_fromUtf8("sbType"))
        self.gridLayout_5.addWidget(self.sbType, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.wEdgeType)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.rbTypeFromLayer = QtGui.QRadioButton(self.wEdgeType)
        self.rbTypeFromLayer.setChecked(False)
        self.rbTypeFromLayer.setObjectName(_fromUtf8("rbTypeFromLayer"))
        self.gridLayout_5.addWidget(self.rbTypeFromLayer, 2, 0, 1, 2)
        self.rbTypeFixed = QtGui.QRadioButton(self.wEdgeType)
        self.rbTypeFixed.setChecked(True)
        self.rbTypeFixed.setObjectName(_fromUtf8("rbTypeFixed"))
        self.gridLayout_5.addWidget(self.rbTypeFixed, 1, 0, 1, 1)
        self.cbType = QtGui.QComboBox(self.wEdgeType)
        self.cbType.setEnabled(False)
        self.cbType.setObjectName(_fromUtf8("cbType"))
        self.gridLayout_5.addWidget(self.cbType, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.wEdgeType)
        self.swAlgorithmControls.addWidget(self.pageEasyMesh)
        self.pageTriangle = QtGui.QWidget()
        self.pageTriangle.setObjectName(_fromUtf8("pageTriangle"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pageTriangle)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.wAngle = QtGui.QWidget(self.pageTriangle)
        self.wAngle.setObjectName(_fromUtf8("wAngle"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wAngle)
        self.gridLayout_2.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cbAngle = QtGui.QCheckBox(self.wAngle)
        self.cbAngle.setChecked(True)
        self.cbAngle.setObjectName(_fromUtf8("cbAngle"))
        self.gridLayout_2.addWidget(self.cbAngle, 0, 0, 1, 1)
        self.sbAngle = QtGui.QDoubleSpinBox(self.wAngle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbAngle.sizePolicy().hasHeightForWidth())
        self.sbAngle.setSizePolicy(sizePolicy)
        self.sbAngle.setMinimumSize(QtCore.QSize(59, 0))
        self.sbAngle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbAngle.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.sbAngle.setAccelerated(True)
        self.sbAngle.setDecimals(1)
        self.sbAngle.setMaximum(34.0)
        self.sbAngle.setSingleStep(1.0)
        self.sbAngle.setProperty("value", 30.0)
        self.sbAngle.setObjectName(_fromUtf8("sbAngle"))
        self.gridLayout_2.addWidget(self.sbAngle, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.verticalLayout_3.addWidget(self.wAngle)
        self.wArea = QtGui.QWidget(self.pageTriangle)
        self.wArea.setObjectName(_fromUtf8("wArea"))
        self.gridLayout_4 = QtGui.QGridLayout(self.wArea)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.rbAreaFixed = QtGui.QRadioButton(self.wArea)
        self.rbAreaFixed.setChecked(True)
        self.rbAreaFixed.setObjectName(_fromUtf8("rbAreaFixed"))
        self.gridLayout_4.addWidget(self.rbAreaFixed, 1, 0, 1, 1)
        self.leArea = QtGui.QLineEdit(self.wArea)
        self.leArea.setObjectName(_fromUtf8("leArea"))
        self.gridLayout_4.addWidget(self.leArea, 1, 1, 1, 1)
        self.rbAreaFromLayer = QtGui.QRadioButton(self.wArea)
        self.rbAreaFromLayer.setObjectName(_fromUtf8("rbAreaFromLayer"))
        self.gridLayout_4.addWidget(self.rbAreaFromLayer, 2, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.wArea)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 2)
        self.cbArea = QtGui.QComboBox(self.wArea)
        self.cbArea.setEnabled(False)
        self.cbArea.setObjectName(_fromUtf8("cbArea"))
        self.gridLayout_4.addWidget(self.cbArea, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.wArea)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.swAlgorithmControls.addWidget(self.pageTriangle)
        self.verticalLayout.addWidget(self.swAlgorithmControls)
        self.line = QtGui.QFrame(MeshToolsPlugin)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(MeshToolsPlugin)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.leOutputFileName = QtGui.QLineEdit(MeshToolsPlugin)
        self.leOutputFileName.setObjectName(_fromUtf8("leOutputFileName"))
        self.horizontalLayout_3.addWidget(self.leOutputFileName)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.widget = QtGui.QWidget(MeshToolsPlugin)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pbGenerate = QtGui.QPushButton(self.widget)
        self.pbGenerate.setMinimumSize(QtCore.QSize(98, 0))
        self.pbGenerate.setObjectName(_fromUtf8("pbGenerate"))
        self.horizontalLayout_2.addWidget(self.pbGenerate)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(MeshToolsPlugin)
        self.swAlgorithmControls.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MeshToolsPlugin.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MeshToolsPlugin.reject)
        QtCore.QObject.connect(self.cbAlgorithm, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.swAlgorithmControls.setCurrentIndex)
        QtCore.QObject.connect(self.rbLengthFixed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.leLength.setEnabled)
        QtCore.QObject.connect(self.rbLengthFromLayer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cbLength.setEnabled)
        QtCore.QObject.connect(self.rbTypeFixed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sbType.setEnabled)
        QtCore.QObject.connect(self.rbTypeFromLayer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cbType.setEnabled)
        QtCore.QObject.connect(self.rbAreaFixed, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.leArea.setEnabled)
        QtCore.QObject.connect(self.rbAreaFromLayer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cbArea.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MeshToolsPlugin)

    def retranslateUi(self, MeshToolsPlugin):
        MeshToolsPlugin.setWindowTitle(QtGui.QApplication.translate("MeshToolsPlugin", "Generate Mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MeshToolsPlugin", "Domain boundary layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Polygons", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNewPolygons_2.setText(QtGui.QApplication.translate("MeshToolsPlugin", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MeshToolsPlugin", "Refinement layers", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNewLines.setText(QtGui.QApplication.translate("MeshToolsPlugin", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Polygons", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNewPolygons.setText(QtGui.QApplication.translate("MeshToolsPlugin", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Points", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNewPoints.setText(QtGui.QApplication.translate("MeshToolsPlugin", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Edge Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.rbLengthFromLayer.setText(QtGui.QApplication.translate("MeshToolsPlugin", "From layer property", None, QtGui.QApplication.UnicodeUTF8))
        self.rbLengthFixed.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Fixed value", None, QtGui.QApplication.UnicodeUTF8))
        self.leLength.setText(QtGui.QApplication.translate("MeshToolsPlugin", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Edge Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.rbTypeFromLayer.setText(QtGui.QApplication.translate("MeshToolsPlugin", "From layer property", None, QtGui.QApplication.UnicodeUTF8))
        self.rbTypeFixed.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Fixed value", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAngle.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Minimum corner angle", None, QtGui.QApplication.UnicodeUTF8))
        self.rbAreaFixed.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Fixed value", None, QtGui.QApplication.UnicodeUTF8))
        self.rbAreaFromLayer.setText(QtGui.QApplication.translate("MeshToolsPlugin", "From layer property", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Minimum triangle area", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.pbGenerate.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Generate mesh", None, QtGui.QApplication.UnicodeUTF8))

