# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_meshtoolsplugin.ui'
#
# Created: Thu Jun  6 16:33:40 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MeshToolsPlugin(object):
    def setupUi(self, MeshToolsPlugin):
        MeshToolsPlugin.setObjectName(_fromUtf8("MeshToolsPlugin"))
        MeshToolsPlugin.resize(385, 565)
        self.verticalLayout = QtGui.QVBoxLayout(MeshToolsPlugin)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_6 = QtGui.QLabel(MeshToolsPlugin)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.cbAlgorithm = QtGui.QComboBox(MeshToolsPlugin)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbAlgorithm.sizePolicy().hasHeightForWidth())
        self.cbAlgorithm.setSizePolicy(sizePolicy)
        self.cbAlgorithm.setObjectName(_fromUtf8("cbAlgorithm"))
        self.horizontalLayout.addWidget(self.cbAlgorithm)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtGui.QFrame(MeshToolsPlugin)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.swAlgorithmControls = QtGui.QStackedWidget(MeshToolsPlugin)
        self.swAlgorithmControls.setFrameShape(QtGui.QFrame.NoFrame)
        self.swAlgorithmControls.setFrameShadow(QtGui.QFrame.Plain)
        self.swAlgorithmControls.setObjectName(_fromUtf8("swAlgorithmControls"))
        self.pageEasyMesh = QtGui.QWidget()
        self.pageEasyMesh.setObjectName(_fromUtf8("pageEasyMesh"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pageEasyMesh)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.wEdgeLength = QtGui.QWidget(self.pageEasyMesh)
        self.wEdgeLength.setEnabled(True)
        self.wEdgeLength.setObjectName(_fromUtf8("wEdgeLength"))
        self.gridLayout_3 = QtGui.QGridLayout(self.wEdgeLength)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.wEdgeLength)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.cbLines = QtGui.QComboBox(self.groupBox)
        self.cbLines.setObjectName(_fromUtf8("cbLines"))
        self.gridLayout_6.addWidget(self.cbLines, 1, 1, 1, 1)
        self.pbNewLines = QtGui.QPushButton(self.groupBox)
        self.pbNewLines.setObjectName(_fromUtf8("pbNewLines"))
        self.gridLayout_6.addWidget(self.pbNewLines, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        self.cbPolygons = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbPolygons.sizePolicy().hasHeightForWidth())
        self.cbPolygons.setSizePolicy(sizePolicy)
        self.cbPolygons.setObjectName(_fromUtf8("cbPolygons"))
        self.gridLayout_6.addWidget(self.cbPolygons, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.pbNewPolygons = QtGui.QPushButton(self.groupBox)
        self.pbNewPolygons.setObjectName(_fromUtf8("pbNewPolygons"))
        self.gridLayout_6.addWidget(self.pbNewPolygons, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_6.addWidget(self.label_3, 2, 0, 1, 1)
        self.cbPoints = QtGui.QComboBox(self.groupBox)
        self.cbPoints.setObjectName(_fromUtf8("cbPoints"))
        self.gridLayout_6.addWidget(self.cbPoints, 2, 1, 1, 1)
        self.pbNewPoints = QtGui.QPushButton(self.groupBox)
        self.pbNewPoints.setObjectName(_fromUtf8("pbNewPoints"))
        self.gridLayout_6.addWidget(self.pbNewPoints, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(self.wEdgeLength)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.cbBoundaryPolygons = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbBoundaryPolygons.sizePolicy().hasHeightForWidth())
        self.cbBoundaryPolygons.setSizePolicy(sizePolicy)
        self.cbBoundaryPolygons.setObjectName(_fromUtf8("cbBoundaryPolygons"))
        self.gridLayout.addWidget(self.cbBoundaryPolygons, 0, 1, 1, 1)
        self.pbNewPolygons_2 = QtGui.QPushButton(self.groupBox_2)
        self.pbNewPolygons_2.setObjectName(_fromUtf8("pbNewPolygons_2"))
        self.gridLayout.addWidget(self.pbNewPolygons_2, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(self.wEdgeLength)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_7.addWidget(self.label_10, 0, 0, 1, 1)
        self.leLength = QtGui.QLineEdit(self.groupBox_3)
        self.leLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leLength.setObjectName(_fromUtf8("leLength"))
        self.gridLayout_7.addWidget(self.leLength, 0, 1, 1, 1)
        self.chkbLengthFromLayer = QtGui.QCheckBox(self.groupBox_3)
        self.chkbLengthFromLayer.setChecked(False)
        self.chkbLengthFromLayer.setObjectName(_fromUtf8("chkbLengthFromLayer"))
        self.gridLayout_7.addWidget(self.chkbLengthFromLayer, 1, 0, 1, 1)
        self.cbLength = QtGui.QComboBox(self.groupBox_3)
        self.cbLength.setEnabled(False)
        self.cbLength.setObjectName(_fromUtf8("cbLength"))
        self.gridLayout_7.addWidget(self.cbLength, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.wEdgeLength)
        self.groupBox_4 = QtGui.QGroupBox(self.pageEasyMesh)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 0, 0, 1, 1)
        self.sbType = QtGui.QSpinBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbType.sizePolicy().hasHeightForWidth())
        self.sbType.setSizePolicy(sizePolicy)
        self.sbType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbType.setMinimum(0)
        self.sbType.setMaximum(9999)
        self.sbType.setProperty("value", 1)
        self.sbType.setObjectName(_fromUtf8("sbType"))
        self.gridLayout_8.addWidget(self.sbType, 0, 1, 1, 1)
        self.chkbTypeFromLayer = QtGui.QCheckBox(self.groupBox_4)
        self.chkbTypeFromLayer.setChecked(False)
        self.chkbTypeFromLayer.setObjectName(_fromUtf8("chkbTypeFromLayer"))
        self.gridLayout_8.addWidget(self.chkbTypeFromLayer, 1, 0, 1, 1)
        self.cbType = QtGui.QComboBox(self.groupBox_4)
        self.cbType.setEnabled(False)
        self.cbType.setObjectName(_fromUtf8("cbType"))
        self.gridLayout_8.addWidget(self.cbType, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.wEdgeType = QtGui.QWidget(self.pageEasyMesh)
        self.wEdgeType.setEnabled(True)
        self.wEdgeType.setObjectName(_fromUtf8("wEdgeType"))
        self.gridLayout_5 = QtGui.QGridLayout(self.wEdgeType)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setVerticalSpacing(3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_2.addWidget(self.wEdgeType)
        self.swAlgorithmControls.addWidget(self.pageEasyMesh)
        self.pageTriangle = QtGui.QWidget()
        self.pageTriangle.setObjectName(_fromUtf8("pageTriangle"))
        self.gridLayout_12 = QtGui.QGridLayout(self.pageTriangle)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.wArea = QtGui.QWidget(self.pageTriangle)
        self.wArea.setObjectName(_fromUtf8("wArea"))
        self.gridLayout_4 = QtGui.QGridLayout(self.wArea)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_7 = QtGui.QGroupBox(self.wArea)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_13.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.cbTriangleRefinementPoints = QtGui.QComboBox(self.groupBox_7)
        self.cbTriangleRefinementPoints.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTriangleRefinementPoints.sizePolicy().hasHeightForWidth())
        self.cbTriangleRefinementPoints.setSizePolicy(sizePolicy)
        self.cbTriangleRefinementPoints.setObjectName(_fromUtf8("cbTriangleRefinementPoints"))
        self.gridLayout_13.addWidget(self.cbTriangleRefinementPoints, 2, 2, 1, 1)
        self.pbTriangleRefinementNewPoints = QtGui.QPushButton(self.groupBox_7)
        self.pbTriangleRefinementNewPoints.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbTriangleRefinementNewPoints.sizePolicy().hasHeightForWidth())
        self.pbTriangleRefinementNewPoints.setSizePolicy(sizePolicy)
        self.pbTriangleRefinementNewPoints.setObjectName(_fromUtf8("pbTriangleRefinementNewPoints"))
        self.gridLayout_13.addWidget(self.pbTriangleRefinementNewPoints, 2, 3, 1, 1)
        self.leTriangleArea = QtGui.QLineEdit(self.groupBox_7)
        self.leTriangleArea.setObjectName(_fromUtf8("leTriangleArea"))
        self.gridLayout_13.addWidget(self.leTriangleArea, 0, 2, 1, 2)
        self.cbTriangleArea = QtGui.QComboBox(self.groupBox_7)
        self.cbTriangleArea.setEnabled(False)
        self.cbTriangleArea.setObjectName(_fromUtf8("cbTriangleArea"))
        self.gridLayout_13.addWidget(self.cbTriangleArea, 4, 2, 1, 1)
        self.rbTriangleAreaDefault = QtGui.QRadioButton(self.groupBox_7)
        self.rbTriangleAreaDefault.setChecked(True)
        self.rbTriangleAreaDefault.setObjectName(_fromUtf8("rbTriangleAreaDefault"))
        self.gridLayout_13.addWidget(self.rbTriangleAreaDefault, 0, 0, 1, 1)
        self.rbTriangleAreaFromLayer = QtGui.QRadioButton(self.groupBox_7)
        self.rbTriangleAreaFromLayer.setChecked(False)
        self.rbTriangleAreaFromLayer.setObjectName(_fromUtf8("rbTriangleAreaFromLayer"))
        self.gridLayout_13.addWidget(self.rbTriangleAreaFromLayer, 2, 0, 1, 1)
        self.labelTriangleAreaAttribute = QtGui.QLabel(self.groupBox_7)
        self.labelTriangleAreaAttribute.setEnabled(False)
        self.labelTriangleAreaAttribute.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTriangleAreaAttribute.setObjectName(_fromUtf8("labelTriangleAreaAttribute"))
        self.gridLayout_13.addWidget(self.labelTriangleAreaAttribute, 4, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_7, 0, 0, 1, 2)
        self.gridLayout_12.addWidget(self.wArea, 3, 0, 2, 3)
        self.groupBox_5 = QtGui.QGroupBox(self.pageTriangle)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_9.addWidget(self.label_11, 0, 0, 1, 1)
        self.cbTriangleBoundaryPolygons = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTriangleBoundaryPolygons.sizePolicy().hasHeightForWidth())
        self.cbTriangleBoundaryPolygons.setSizePolicy(sizePolicy)
        self.cbTriangleBoundaryPolygons.setObjectName(_fromUtf8("cbTriangleBoundaryPolygons"))
        self.gridLayout_9.addWidget(self.cbTriangleBoundaryPolygons, 0, 1, 1, 1)
        self.pbTriangleNewPolygons = QtGui.QPushButton(self.groupBox_5)
        self.pbTriangleNewPolygons.setObjectName(_fromUtf8("pbTriangleNewPolygons"))
        self.gridLayout_9.addWidget(self.pbTriangleNewPolygons, 0, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_9.addWidget(self.label_12, 1, 0, 1, 1)
        self.cbTriangleBoundaryLines = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTriangleBoundaryLines.sizePolicy().hasHeightForWidth())
        self.cbTriangleBoundaryLines.setSizePolicy(sizePolicy)
        self.cbTriangleBoundaryLines.setObjectName(_fromUtf8("cbTriangleBoundaryLines"))
        self.gridLayout_9.addWidget(self.cbTriangleBoundaryLines, 1, 1, 1, 1)
        self.pbTriangleNewLines = QtGui.QPushButton(self.groupBox_5)
        self.pbTriangleNewLines.setObjectName(_fromUtf8("pbTriangleNewLines"))
        self.gridLayout_9.addWidget(self.pbTriangleNewLines, 1, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_9.addWidget(self.label_13, 2, 0, 1, 1)
        self.cbTriangleBoundaryPoints = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTriangleBoundaryPoints.sizePolicy().hasHeightForWidth())
        self.cbTriangleBoundaryPoints.setSizePolicy(sizePolicy)
        self.cbTriangleBoundaryPoints.setObjectName(_fromUtf8("cbTriangleBoundaryPoints"))
        self.gridLayout_9.addWidget(self.cbTriangleBoundaryPoints, 2, 1, 1, 1)
        self.pbTriangleNewPoints = QtGui.QPushButton(self.groupBox_5)
        self.pbTriangleNewPoints.setObjectName(_fromUtf8("pbTriangleNewPoints"))
        self.gridLayout_9.addWidget(self.pbTriangleNewPoints, 2, 2, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_5, 0, 0, 2, 3)
        self.wAngle = QtGui.QWidget(self.pageTriangle)
        self.wAngle.setObjectName(_fromUtf8("wAngle"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wAngle)
        self.gridLayout_2.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cbTriangleAngle = QtGui.QCheckBox(self.wAngle)
        self.cbTriangleAngle.setChecked(True)
        self.cbTriangleAngle.setObjectName(_fromUtf8("cbTriangleAngle"))
        self.gridLayout_2.addWidget(self.cbTriangleAngle, 0, 0, 1, 1)
        self.sbTriangleAngle = QtGui.QDoubleSpinBox(self.wAngle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbTriangleAngle.sizePolicy().hasHeightForWidth())
        self.sbTriangleAngle.setSizePolicy(sizePolicy)
        self.sbTriangleAngle.setMinimumSize(QtCore.QSize(59, 0))
        self.sbTriangleAngle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbTriangleAngle.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.sbTriangleAngle.setAccelerated(True)
        self.sbTriangleAngle.setDecimals(1)
        self.sbTriangleAngle.setMaximum(34.0)
        self.sbTriangleAngle.setSingleStep(1.0)
        self.sbTriangleAngle.setProperty("value", 30.0)
        self.sbTriangleAngle.setObjectName(_fromUtf8("sbTriangleAngle"))
        self.gridLayout_2.addWidget(self.sbTriangleAngle, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_12.addWidget(self.wAngle, 2, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem, 5, 1, 1, 1)
        self.swAlgorithmControls.addWidget(self.pageTriangle)
        self.verticalLayout.addWidget(self.swAlgorithmControls)
        self.line = QtGui.QFrame(MeshToolsPlugin)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(MeshToolsPlugin)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.leMeshName = QtGui.QLineEdit(MeshToolsPlugin)
        self.leMeshName.setObjectName(_fromUtf8("leMeshName"))
        self.horizontalLayout_3.addWidget(self.leMeshName)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.widget = QtGui.QWidget(MeshToolsPlugin)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pbGenerate = QtGui.QPushButton(self.widget)
        self.pbGenerate.setMinimumSize(QtCore.QSize(98, 0))
        self.pbGenerate.setObjectName(_fromUtf8("pbGenerate"))
        self.horizontalLayout_2.addWidget(self.pbGenerate)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(MeshToolsPlugin)
        self.swAlgorithmControls.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MeshToolsPlugin.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MeshToolsPlugin.reject)
        QtCore.QObject.connect(self.cbAlgorithm, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.swAlgorithmControls.setCurrentIndex)
        QtCore.QObject.connect(self.chkbLengthFromLayer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cbLength.setEnabled)
        QtCore.QObject.connect(self.chkbTypeFromLayer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cbType.setEnabled)
        QtCore.QObject.connect(self.rbTriangleAreaFromLayer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cbTriangleRefinementPoints.setEnabled)
        QtCore.QObject.connect(self.rbTriangleAreaFromLayer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pbTriangleRefinementNewPoints.setEnabled)
        QtCore.QObject.connect(self.rbTriangleAreaFromLayer, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cbTriangleArea.setEnabled)
        QtCore.QObject.connect(self.rbTriangleAreaDefault, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.labelTriangleAreaAttribute.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MeshToolsPlugin)

    def retranslateUi(self, MeshToolsPlugin):
        MeshToolsPlugin.setWindowTitle(QtGui.QApplication.translate("MeshToolsPlugin", "Generate Mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MeshToolsPlugin", "Refinement layers", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNewLines.setText(QtGui.QApplication.translate("MeshToolsPlugin", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Polygons", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNewPolygons.setText(QtGui.QApplication.translate("MeshToolsPlugin", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Points", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNewPoints.setText(QtGui.QApplication.translate("MeshToolsPlugin", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MeshToolsPlugin", "Domain boundary layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Polygons", None, QtGui.QApplication.UnicodeUTF8))
        self.pbNewPolygons_2.setText(QtGui.QApplication.translate("MeshToolsPlugin", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MeshToolsPlugin", "Triangle edge length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Default value in map units", None, QtGui.QApplication.UnicodeUTF8))
        self.leLength.setText(QtGui.QApplication.translate("MeshToolsPlugin", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.chkbLengthFromLayer.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Use value from layer property", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MeshToolsPlugin", "Edge / point type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Default type", None, QtGui.QApplication.UnicodeUTF8))
        self.chkbTypeFromLayer.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Use type from layer property", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MeshToolsPlugin", "Maximum triangle area", None, QtGui.QApplication.UnicodeUTF8))
        self.pbTriangleRefinementNewPoints.setText(QtGui.QApplication.translate("MeshToolsPlugin", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.leTriangleArea.setText(QtGui.QApplication.translate("MeshToolsPlugin", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.rbTriangleAreaDefault.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Default value", None, QtGui.QApplication.UnicodeUTF8))
        self.rbTriangleAreaFromLayer.setText(QtGui.QApplication.translate("MeshToolsPlugin", "From points layer", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTriangleAreaAttribute.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MeshToolsPlugin", "Domain boundary / breaklines layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Polygons", None, QtGui.QApplication.UnicodeUTF8))
        self.pbTriangleNewPolygons.setText(QtGui.QApplication.translate("MeshToolsPlugin", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.pbTriangleNewLines.setText(QtGui.QApplication.translate("MeshToolsPlugin", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Points", None, QtGui.QApplication.UnicodeUTF8))
        self.pbTriangleNewPoints.setText(QtGui.QApplication.translate("MeshToolsPlugin", "New...", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTriangleAngle.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Minimum corner angle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.pbGenerate.setText(QtGui.QApplication.translate("MeshToolsPlugin", "Generate mesh", None, QtGui.QApplication.UnicodeUTF8))

